/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cement_opengl_stl_NativeStlReader */

#ifndef _Included_com_cement_opengl_stl_NativeStlReader
#define _Included_com_cement_opengl_stl_NativeStlReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cement_opengl_stl_NativeStlReader
 * Method:    nativeReadFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cement_opengl_stl_NativeStlReader_nativeReadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cement_opengl_stl_NativeStlReader
 * Method:    transmitFilePath
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cement_opengl_stl_NativeStlReader_transmitFilePath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
