/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cement_opengl_stl_NativeRenderer */

#ifndef _Included_com_cement_opengl_stl_NativeRenderer
#define _Included_com_cement_opengl_stl_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cement_opengl_stl_NativeRenderer
 * Method:    nativeSurfaceDrawing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_opengl_stl_NativeRenderer_nativeSurfaceDrawing
  (JNIEnv *, jobject);

/*
 * Class:     com_cement_opengl_stl_NativeRenderer
 * Method:    nativeSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_opengl_stl_NativeRenderer_nativeSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_cement_opengl_stl_NativeRenderer
 * Method:    nativeSurfacechanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_opengl_stl_NativeRenderer_nativeSurfacechanged
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
