/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cement_jni_NaiveFileReader */

#ifndef _Included_com_cement_jni_NaiveFileReader
#define _Included_com_cement_jni_NaiveFileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cement_jni_NaiveFileReader
 * Method:    NativeFileOpen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cement_jni_NaiveFileReader_NativeFileOpen
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_cement_jni_NaiveFileReader
 * Method:    NativeFileRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_cement_jni_NaiveFileReader_NativeFileRead
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_cement_jni_NaiveFileReader
 * Method:    NativeFileWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_cement_jni_NaiveFileReader_NativeFileWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_cement_jni_NaiveFileReader
 * Method:    NativeFileSeek
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_com_cement_jni_NaiveFileReader_NativeFileSeek
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     com_cement_jni_NaiveFileReader
 * Method:    NativeFileClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cement_jni_NaiveFileReader_NativeFileClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
