/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cement_jni_NativeRenderer */
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

#ifndef _Included_com_cement_jni_NativeRenderer
#define _Included_com_cement_jni_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cement_jni_NativeRenderer
 * Method:    drawStlModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cement_jni_NativeRenderer_drawStlModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_cement_jni_NativeRenderer
 * Method:    surfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_jni_NativeRenderer_surfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_cement_jni_NativeRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cement_jni_NativeRenderer_surfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_cement_jni_NativeRenderer
 * Method:    surfaceDrawing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_jni_NativeRenderer_surfaceDrawing
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
